name: Production Pipeline

on:
  push:
    branches:
      - main # Automatically trigger on push to main branch (production)

jobs:
  build-and-deploy-production:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    environment: 
      name: Production

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean Container Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Pull Docker image from registry (re-use the image built in staging)
      - name: Pull Docker image from registry
        run: |
          docker pull ${{ secrets.DOCKER_REGISTRY }}/my-app:latest

      # Step 4: Push Docker image to DigitalOcean (tagging it for production)
      - name: Push Docker image to DigitalOcean
        run: |
          docker tag ${{ secrets.DOCKER_REGISTRY }}/my-app:latest ${{ secrets.DOCKER_REGISTRY }}/my-app:production
          docker push ${{ secrets.DOCKER_REGISTRY }}/my-app:production

     
